### ISSUE TITLE
How can I set the order of the data tour elements?

### ISSUE THREAD

**Issue by wzol** [crash83k/jquery-page-tour#1]
I've checked the demo, and it seems to work really nicely - one thing I couldn't figure out is how can I set the order of the tour elements? Is there a data-tour-order or some different parameter? If there isn't, is it possible for you to add something similar?

**Comment by crash83k** [comment]
At the moment, there's no way to do it. In an older version, there definitely was a way because I was pushing an array object instead of using discovery. I think I can reimplement that instead of using discovery. Then you would push an array of objects to the library on initialization. Something like,

```javascript
[
  {
    dom: 'selector',
    title: 'title',
    desc: 'description'
  },
  {
    dom: 'selector',
    title: 'title',
    desc: 'description'
  },
 ... 
]
```

**Comment by wzol** [comment]
To be honest I really like the way, that you managed to build it in a way so that all the needed data could stay inside the DOM with the content, and JS is only needed for the inner workings. Somehow it feels weird for me to put the title and description inside the JS, for example if you have 10 tours on a site, that would make the JS quite big, also it can be even worse if the site is multilingual. I feel that it would be more natural to use a data attribute for just ordering, and the next function would find the next item to highlight.

What do you think?

**Comment by crash83k** [comment]
Yeah, that's a really good idea. Shouldn't be hard to do, either. So it could be `data-tour-index="1"`.

**Comment by wzol** [comment]
I think that would be great. If you could manage to do it in a way that if one is missing then auto skip to the next one which exists (like: 1 2 3 6 7 8) then it would auto handle responsive sites too where example step 4 and 5 are in the sidebar and the sidebar is hidden/doesn't exist because of screen width.

**Comment by crash83k** [comment]
I did a basic JS array sort. So any elements that don't have an index are automatically put at the end. Items with an index are ordered in the ASC order of their index. So if you had 5 elements, 3 with indexes, they might be seen like this:
`[null, 4, 2, null, 8]`
but be ordered:
`[2, 4, 8, null, null]`

I just pushed this change. Let me know how it goes.

**Comment by wzol** [comment]
I'm trying it but I've run into another problem - I open another issue for it.

**Comment by crash83k** [comment]
Closing the issue. The index is working as expected. :+1:
