### ISSUE TITLE
discoverDom and tour init seems to run at script include

### ISSUE THREAD

**Issue by wzol** [crash83k/jquery-page-tour#2]
I'm trying to set up a tour, but as I put all my scripts into the header, the script seems to run the init instantly, so it can't find any tour elements (as the page isn't build yet). As the usual method is including the scripts into the header or in the footer could you make the init call manual? Like a `PageTour.setup` followed by the `PageTour.open`.

**Comment by wzol** [comment]
Well, it seems `PageTour.rediscover()` would do just what I need. I need to try it.

**Comment by wzol** [comment]
Unfortunately I couldn't make it work: the `rediscover()` seems to help a bit - at least there is no "No tour elements" when calling it, but it only puts an empty string out to the console from `console.log(org.css('font-size'));` and scrolls the page to the element: nothing appears. :(

**Comment by crash83k** [comment]
Makes sense. I'll change it to wait for the page to load completely before starting up. I'm also going to fix the rediscover method.

**Comment by crash83k** [comment]
@wzol, I've pushed a change to do discovery only when the tour is started. Give it a try and let me know if this works well for you.

**Comment by crash83k** [comment]
The discovery seems to be working and I haven't heard back about any issues. :+1:
